---
--- Generated by Luanalysis
--- Created by a1876.
--- DateTime: 2023/3/9 15:11
---
local articleId = ARGV[1]
local userId = ARGV[2]
local likeSet = ARGV[3]
local dislikeSet = ARGV[4]
local waitPushLike = ARGV[5]
local waitPushDeleteLike = ARGV[6]
local waitPushDislike = ARGV[7]
local waitPushDeleteDislike = ARGV[8]
local type = ARGV[9]

if (type == 'true') then
    redis.call('SREM', likeSet .. articleId, userId)
    if (tonumber(redis.call('SREM', waitPushLike .. articleId, userId)) == 1) then
        return
    end
    redis.call('SADD', waitPushDeleteLike .. articleId, userId)
    return 1
end

redis.call('SREM', dislikeSet .. articleId, userId)
if (tonumber(redis.call('SREM', waitPushDislike .. articleId, userId)) == 1) then
    return
end
redis.call('SADD', waitPushDeleteDislike .. articleId, userId)
return 0