server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.107:3306/blog?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
